"""open-jaw return legs

Revision ID: 6e8b4ccadddd
Revises: e3f8a12b90d4
Create Date: 2026-07-16 17:18:55.967383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8b4ccadddd'
down_revision: Union[str, Sequence[str], None] = 'e3f8a12b90d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('leg', sa.String(), nullable=True))
    op.add_column('price_watches', sa.Column('return_origin', sa.String(length=3), nullable=True))
    op.add_column('price_watches', sa.Column('return_destination', sa.String(length=3), nullable=True))
    op.add_column('searches', sa.Column('return_origin', sa.String(length=3), nullable=True))
    op.add_column('searches', sa.Column('return_destination', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'return_destination')
    op.drop_column('searches', 'return_origin')
    op.drop_column('price_watches', 'return_destination')
    op.drop_column('price_watches', 'return_origin')
    op.drop_column('flight_offers', 'leg')
    # ### end Alembic commands ###
