"""initial schema

Revision ID: ca11fc964b29
Revises: 
Create Date: 2026-04-27 20:47:43.304003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca11fc964b29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alliance', sa.String(), nullable=True),
    sa.Column('is_regional', sa.Boolean(), nullable=False),
    sa.Column('direct_booking_url', sa.String(), nullable=True),
    sa.Column('loyalty_program', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('nearby_airports', sa.ARRAY(sa.String(length=3)), nullable=True),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('points_programs',
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=True),
    sa.Column('transfer_partners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_name')
    )
    op.create_table('price_history',
    sa.Column('route_key', sa.String(), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('days_until_departure', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_departure', 'price_history', ['route_key', 'days_until_departure'], unique=False)
    op.create_index('idx_price_history_route', 'price_history', ['route_key', 'recorded_at'], unique=False)
    op.create_table('searches',
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('flex_days', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('include_nearby', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_offers',
    sa.Column('search_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_duration', sa.Interval(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fare_type', sa.String(), nullable=True),
    sa.Column('booking_url', sa.String(), nullable=True),
    sa.Column('deep_link', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_offers')
    op.drop_table('searches')
    op.drop_index('idx_price_history_route', table_name='price_history')
    op.drop_index('idx_price_history_departure', table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('points_programs')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
