"""`flightdeck db` — database lifecycle commands.

Wraps Alembic migrations and seed scripts so the user has one tool to
provision a clean database without remembering subcommands.
"""
from __future__ import annotations

import asyncio
import subprocess
import sys
from pathlib import Path

import click

from app.cli.client import fail
from app.cli.output import console

REPO_ROOT = Path(__file__).resolve().parents[3]


def _run_alembic(*args: str) -> None:
    """Invoke Alembic from the repo root so it picks up alembic.ini."""
    cmd = [sys.executable, "-m", "alembic", *args]
    result = subprocess.run(cmd, cwd=REPO_ROOT, check=False)
    if result.returncode != 0:
        fail(f"alembic {' '.join(args)} failed (exit {result.returncode})")


@click.group("db", help="Database lifecycle: init, seed, migrate, downgrade.")
def db_cmd() -> None:
    pass


@db_cmd.command("init", help="Apply all migrations to bring the DB to head.")
def db_init() -> None:
    console.print("[bold]Applying migrations...[/bold]")
    _run_alembic("upgrade", "head")
    console.print("[green]✓ Database is at head.[/green]")


@db_cmd.command("downgrade", help="Roll back one migration.")
@click.option("--to", "to_rev", default="-1", help="Target revision (default: -1).")
def db_downgrade(to_rev: str) -> None:
    console.print(f"[bold]Downgrading to {to_rev}...[/bold]")
    _run_alembic("downgrade", to_rev)


@db_cmd.command("revision", help="Generate a new autogenerated migration.")
@click.option("--message", "-m", required=True, help="Short description of the change.")
def db_revision(message: str) -> None:
    _run_alembic("revision", "--autogenerate", "-m", message)


@db_cmd.command("seed", help="Seed reference data (airports, points programs).")
def db_seed() -> None:
    from scripts.seed_airports import seed as seed_airports
    from scripts.seed_transfer_partners import seed as seed_transfer

    async def _run() -> None:
        n_airports = await seed_airports()
        console.print(f"[green]✓[/green] Seeded {n_airports} airports.")
        n_programs = await seed_transfer()
        console.print(f"[green]✓[/green] Seeded {n_programs} points programs.")

    asyncio.run(_run())
